services:
  scylla:
    image: scylladb/scylla:latest
    container_name: riset-scylla
    restart: unless-stopped
    ports:
      - "9042:9042"
    command: --smp 1 --overprovisioned 1 --developer-mode 1
    volumes:
      - scylla-data:/var/lib/scylla
    ulimits:
      memlock: -1
      nofile:
        soft: 65535
        hard: 65535

volumes:
  scylla-data:
    driver: local
